version: '3.4'

services:
  breakfastapi:
    image: breakfastapi
    container_name: BreakfastAPI
    ports:
      - "80:8080"
      - "81:8081"
    build:
      context: .
      dockerfile: BreakfastAPI/Dockerfile
      target: final
  breakfastapi_unittest:
    image: breakfastapi_unittest
    container_name: BreakfastAPI_UnitTest
    build:
      context: .
      dockerfile: BreakfastAPI/Dockerfile
      target: unittest
    volumes:
        - ./TestResult:/TestResults
    #for debug propose
    #command: tail -F anything 
  breakfastapi_publish:
    image: breakfastapi_publish
    container_name: BreakfastAPI_Publish
    build:
      context: .
      dockerfile: BreakfastAPI/Dockerfile
      target: publish
    volumes:
      - ./Publish:/Publish